# Spring Boot configuration
spring.application.name=ms-core-app

# Database configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://sursell-sharkburger-db.cm762cwmuy8a.us-east-1.rds.amazonaws.com:5432/sharkburger_db
spring.datasource.username=sursell_admin
spring.datasource.password=fC0Pl<<j#i7df_eT]4yeONSKUtqF
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server configuration
server.port=8083

# Swagger UI and OpenAPI configuration
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/openapi
springdoc.swagger-ui.operations-sorter=alpha

# Logging
logging.level.root=INFO
logging.level.com.suresell.mscoreapp=DEBUG
