server:
  port: 8083
  servlet:
    context-path: /api/core

spring:
  application:
    name: ms-core-app

  datasource:
    url: jdbc:postgresql://sursell-sharkburger-db.cm762cwmuy8a.us-east-1.rds.amazonaws.com:5432/sharkburger_db?serverTimezone=GMT-5
    username: sursell_admin
    password: wX:]WS6iu16g3sR<a2v1-fFsjyI>
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 4
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    try-it-out-enabled: true
    display-request-duration: true
  api-docs:
    path: /openapi
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

logging:
  level:
    root: INFO
    com.suresell.mscoreapp: DEBUG