# Spring Boot configuration
spring.application.name=ms-core-app

# Database configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://ls-8f03f5dffeb6c68ede20f6f03102f58723b67c67.cmlyw6wgewic.us-east-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=suresell_admin
spring.datasource.password=N&PR4P*d-$PND$Hzn;AgM=8FDizGSgcH
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate/JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server configuration
server.port=8083

# Swagger UI and OpenAPI configuration
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/openapi
springdoc.swagger-ui.operations-sorter=alpha

# Logging
logging.level.root=INFO
logging.level.com.suresell.mscoreapp=DEBUG
