-- Esquema con RLS **ABIERTA A PROPÓSITO**, para probar el filtro de aplicación
-- en aislamiento.
--
-- Reproduce el estado REAL de las 17 tablas de administración que creó
-- `V28__tablas_admin_y_numeracion_por_sede.sql:150-164`: RLS activada, pero con
-- la política `USING (true) WITH CHECK (true)`, que no aísla nada. Así están
-- `supplies`, `employees`, `payrolls`, `expenses`, `valeras`,
-- `accounts_receivable` y once más, hasta que se aplique V33.
--
-- POR QUÉ ESTE ARCHIVO. Si se probara el filtro por código contra una tabla con
-- RLS real, el test pasaría aunque el filtro no existiera: estaría midiendo la
-- política, no el código. Con la política abierta, lo ÚNICO que puede aislar es
-- el `WHERE tenant_id = ?` que pone Hibernate. Es la única forma de saber que la
-- defensa en profundidad es real y no decorativa.
--
-- Contrasta con `esquema-waiters-con-rls.sql`, que sí tiene la política real.

CREATE ROLE app_user LOGIN PASSWORD 'app_pw';

CREATE TABLE waiters (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id             TEXT NOT NULL DEFAULT nullif(current_setting('app.tenant_id', true), ''),
    name                  TEXT NOT NULL,
    active                BOOLEAN NOT NULL DEFAULT TRUE,
    daily_sale_goal       NUMERIC(12,2),
    commission_percentage NUMERIC(5,2)
);

ALTER TABLE waiters ENABLE ROW LEVEL SECURITY;

-- ⚠️ ESTA ES LA POLÍTICA ROTA, COPIADA DE V28:161-162. Deliberada.
CREATE POLICY app_rw_waiters ON waiters
    FOR ALL TO app_user
    USING (true) WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE waiters TO app_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_user;
