-- Trozo del esquema REAL de Producción, lo mínimo para probar que el panel
-- puede escribir. Copiado de lo que hay hoy en la base compartida:
--
--   · La política y el FORCE, tal cual (pg_policies el 2026-08-14).
--   · El default de `tenant_id` que dejó V32, con su `nullif`.
--   · El rol `app_user`, que es con el que corre el servicio y a quien RLS
--     sí le aplica. Conectarse como dueño no probaría nada: el dueño con
--     BYPASSRLS se salta la política.
--
-- ms-core-app no tiene migraciones propias (`ddl-auto: none`, el esquema lo
-- maneja Flyway en ms-order-product-mt), así que esto se mantiene a mano.
-- Si la tabla real cambia, este archivo hay que actualizarlo.

CREATE ROLE app_user LOGIN PASSWORD 'app_pw';

CREATE TABLE waiters (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id             TEXT NOT NULL DEFAULT nullif(current_setting('app.tenant_id', true), ''),
    name                  TEXT NOT NULL,
    active                BOOLEAN NOT NULL DEFAULT TRUE,
    daily_sale_goal       NUMERIC(12,2),
    commission_percentage NUMERIC(5,2)
);

ALTER TABLE waiters ENABLE ROW LEVEL SECURITY;
ALTER TABLE waiters FORCE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation_waiters ON waiters
    USING (tenant_id = current_setting('app.tenant_id', true))
    WITH CHECK (tenant_id = current_setting('app.tenant_id', true));

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE waiters TO app_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_user;
